// المصدر الحقيقي لمنيو O2 — منقول كما هو من ملف الموقع (TypeScript)
'use strict';

const categoryNames = {
  shawarma: 'الشاورما',
  italian: 'الإيطالي',
  sandwiches: 'السندويشات الغربية',
  easternSweets: 'الحلويات الشرقية',
  westernSweets: 'الكيك والحلويات الغربية',
  barSweets: 'حلويات البار',
  drinks: 'المشروبات',
  salads: 'السلطات',
  gelato: 'الجيلاتو',
};

const categoryEmoji = {
  shawarma: '🥙', italian: '🍕', sandwiches: '🍔',
  easternSweets: '🍯', westernSweets: '🍰', barSweets: '🧇',
  drinks: '☕', salads: '🥗', gelato: '🍨',
};

const A = (items) => items.map((i) => ({ ...i, active: i.active ?? true }));

/* ══════════════════ فرع غزة ══════════════════ */
const gazaMenu = {
  shawarma: {
    title: 'الشاورما',
    items: A([
      { name: 'بيتا شاورما', price: 10, image: 'https://o2bot-b7a51.web.app/menu/shawarma/54.jpg', active: false },
      { name: 'فرشوحة عادي', price: 15, image: 'https://o2bot-b7a51.web.app/menu/shawarma/48.jpg', active: true },
      { name: 'فرشوحه دبل', price: 17, image: 'https://o2bot-b7a51.web.app/menu/shawarma/49.jpg' },
      { name: 'فرشوحه دبل لحمة', price: 25, image: 'https://o2bot-b7a51.web.app/menu/shawarma/48.jpg' },
      { name: 'فرشوحه دبل دبل', price: 27, image: 'https://o2bot-b7a51.web.app/menu/shawarma/48.jpg' },
      { name: 'سوري', price: 30, image: 'https://o2bot-b7a51.web.app/menu/shawarma/53.jpg' },
      { name: 'صفيحة', price: 35, desc: 'شاورما - جبنة - زيتون اسود', image: 'https://o2bot-b7a51.web.app/menu/shawarma/51.jpg' },
      { name: 'باشكا', price: 40, desc: 'خبزة باشكا - شاورما - جبنة - زيتون - صوص بيكانتي', image: 'https://o2bot-b7a51.web.app/menu/shawarma/18.jpg', active: true },
      { name: 'شاورما عربي', price: 35, desc: 'قطع شاورما - جبنة - زيتون اسود', image: 'https://o2bot-b7a51.web.app/menu/shawarma/17.jpg', active: true },
      { name: 'شاورما نابلسي', price: 35, desc: 'شاورما - بطاطا - صوص بيكانتي - جبنة - زيتون اسود', image: 'https://o2bot-b7a51.web.app/menu/shawarma/19.jpg', active: true },
      { name: 'صحن شاورما', price: 30, image: 'https://o2bot-b7a51.web.app/menu/shawarma/14.jpg' },
      { name: 'صحن شاورما صغير', price: 20, image: 'https://o2bot-b7a51.web.app/menu/shawarma/13.jpg', active: false },
    ]),
  },
  italian: {
    title: 'الإيطالي',
    items: A([
      { name: 'كاليزوني دجاج + شيبس', price: 35, desc: 'صدر دجاج - جبنة - زيتون - رانش', image: 'https://o2bot-b7a51.web.app/menu/italian/91.jpeg' },
      { name: 'كاليزوني خضار', price: 20, desc: 'فليفلة - بصل - ذرة - مشروم - زيتون', image: 'https://o2bot-b7a51.web.app/menu/italian/36.jpg' },
      { name: 'بيتزا مكسيكي دجاج', price: 25, desc: 'صدر دجاج - جبنة - زيتون', image: 'https://o2bot-b7a51.web.app/menu/italian/33.jpg' },
      { name: 'ميجا', price: 35, desc: 'صدر دجاج - فليفلة - مشروم - جرادة - بصل - كريمة طعام', image: 'https://o2bot-b7a51.web.app/menu/italian/34.jpg' },
      { name: 'بيتزا خضار', price: 20, desc: 'خضار - ذرة - زيتون', image: 'https://o2bot-b7a51.web.app/menu/italian/32.jpg', active: true },
      { name: 'بيتزا ماما روزا بالاناناس', price: 20, desc: 'أناناس', image: 'https://o2bot-b7a51.web.app/menu/italian/2.jpg' },
      { name: 'نابولي', price: 20, desc: 'بيتزا بالتونة والزيتون', image: 'https://o2bot-b7a51.web.app/menu/italian/3.jpg' },
      { name: 'مارجريتا', price: 20, desc: 'جبنة', image: 'https://o2bot-b7a51.web.app/menu/italian/1.jpg' },
      { name: 'صوص رانش', price: 3, image: 'https://o2bot-b7a51.web.app/menu/italian/7.jpeg' },
    ]),
  },
  sandwiches: {
    title: 'السندويشات الغربية',
    items: A([
      { name: 'زينجر', price: 30, desc: 'شرائح صدر دجاج متبّلة مع بندورة طازجة، جرجير، حلقات بصل', image: 'https://o2bot-b7a51.web.app/menu/western/44.jpg' },
      { name: 'بيف برجر', price: 30, desc: 'قطعة لحمة - بصل - بندورة - جبنة - مخلل - صوص بيكانتي', image: 'https://o2bot-b7a51.web.app/menu/western/40.jpg' },
      { name: 'بيغ ماك', price: 40, desc: 'قطعتين لحمة - بصل - بندورة - جبنة - مخلل - صوص بيكانتي', image: 'https://o2bot-b7a51.web.app/menu/western/46.jpg' },
      { name: 'تشكن بيتزا', price: 30, desc: 'صدر دجاج - مشروم - فليفلة - بصل - زيتون اسود - جبنة', image: 'https://o2bot-b7a51.web.app/menu/western/94.jpg' },
      { name: 'شيش طاووق', price: 30, desc: 'فخد دجاج - جرجير - بندورة -مخلل -صوص بيكانتي', image: 'https://o2bot-b7a51.web.app/menu/western/47.jpg' },
      { name: 'فطيرة الذهبية', price: 30, desc: 'صدر دجاج - فليفلة - بصل - زيتون اسود - جبنة - ذرة - كريمة طعام', image: 'https://o2bot-b7a51.web.app/menu/western/43.jpg' },
      { name: 'تشكن فرايز', price: 30, image: 'https://o2bot-b7a51.web.app/menu/western/100.png' },
    ]),
  },
  easternSweets: {
    title: 'الحلويات الشرقية',
    byWeight: true,
    items: A([
      { name: 'نمورة', pricePerKg: 20, image: 'https://o2bot-b7a51.web.app/menu/sweets/25.jpeg' },
      { name: 'بسبوسة', pricePerKg: 20, image: 'https://o2bot-b7a51.web.app/menu/sweets/82.jpeg' },
      { name: 'كلاج', pricePerKg: 20, image: 'https://o2bot-b7a51.web.app/menu/sweets/3.1.jpg', desc: 'كلاج - كلاج نوتيلا' },
      { name: 'عش البلبل', pricePerKg: 30, image: 'https://o2bot-b7a51.web.app/menu/sweets/7.jpg' },
      { name: 'كول واشكر', pricePerKg: 30, image: 'https://o2bot-b7a51.web.app/menu/sweets/5.jpg' },
      { name: 'سنيورة', pricePerKg: 30, image: 'https://o2bot-b7a51.web.app/menu/sweets/8.jpg' },
      { name: 'كنافة عربية', pricePerKg: 35, image: 'https://o2bot-b7a51.web.app/menu/sweets/17.jpeg' },
      { name: 'بسبوسة نوتيلا', pricePerKg: 40, image: 'https://o2bot-b7a51.web.app/menu/sweets/18.jpeg' },
      { name: 'بقلاوة لوز', pricePerKg: 48, image: 'https://o2bot-b7a51.web.app/menu/sweets/9.jpg' },
      { name: 'نابلسية', pricePerKg: 40, image: 'https://o2bot-b7a51.web.app/menu/sweets/23.jpg' },
      { name: 'معكوفة لوز', pricePerKg: 35, image: 'https://o2bot-b7a51.web.app/menu/sweets/6.jpg' },
      { name: 'أساور لوز', pricePerKg: 48, image: 'https://o2bot-b7a51.web.app/menu/sweets/19.jpeg' },
      { name: 'صرة', pricePerKg: 35, image: 'https://o2bot-b7a51.web.app/menu/sweets/2.jpg' },
      { name: 'وربات', pricePerKg: 35, image: 'https://o2bot-b7a51.web.app/menu/sweets/26.jpg' },
      { name: 'معكوفة عين جمل', pricePerKg: 35, image: 'https://o2bot-b7a51.web.app/menu/sweets/4.jpg' },
      { name: 'بقلاوة عين جمل', pricePerKg: 55, image: 'https://o2bot-b7a51.web.app/menu/sweets/41.jpg' },
      { name: 'بقلاوة حلبي', pricePerKg: 100, image: 'https://o2bot-b7a51.web.app/menu/sweets/10.jpg' },
      { name: 'كاسات مكسرات', pricePerKg: 80, image: 'https://o2bot-b7a51.web.app/menu/sweets/24.jpg' },
      { name: 'بورما حلبي', pricePerKg: 100, image: 'https://o2bot-b7a51.web.app/menu/sweets/78.jpeg' },
      { name: 'بلورية حلبي', pricePerKg: 130, image: 'https://o2bot-b7a51.web.app/menu/sweets/84.jpeg' },
      { name: 'دولمة حلبي', pricePerKg: 130, image: 'https://o2bot-b7a51.web.app/menu/sweets/27.jpg' },
      { name: 'بلورية حلبي نوتيلا', pricePerKg: 130, image: 'https://o2bot-b7a51.web.app/menu/sweets/92.jpeg' },
      { name: 'دولمة شوكولاتة', pricePerKg: 130, image: 'https://o2bot-b7a51.web.app/menu/sweets/74.jpg' },
    ]),
  },
  westernSweets: {
    title: 'الكيك والحلويات الغربية',
    items: A([
      { name: 'قالب كيك صغير', price: 60, image: 'https://o2bot-b7a51.web.app/menu/cake/9.jpg' },
      { name: 'قالب كيك كبير', price: 80, image: 'https://o2bot-b7a51.web.app/menu/cake/10.jpg' },
      { name: 'قالب كيك اسبيسشل صغير', price: 80, image: 'https://o2bot-b7a51.web.app/menu/cake/38.jpg' },
      { name: 'قالب كيك اسبيسشل كبير', price: 100, image: 'https://o2bot-b7a51.web.app/menu/cake/88.jpeg' },
      { name: 'قطع كيك كلاسيكي', price: 5, image: 'https://o2bot-b7a51.web.app/menu/cake/5.jpg', active: false },
      { name: 'سويس رول', price: 8, image: 'https://o2bot-b7a51.web.app/menu/cake/31.jpg', active: false },
      { name: 'تريلتشا', price: 10, image: 'https://o2bot-b7a51.web.app/menu/cake/21.jpg', active: false },
      { name: 'قطع كيك سبيشل', price: 10, desc: 'نوتيلا / بيستاشيو / لوتس', image: 'https://o2bot-b7a51.web.app/menu/cake/30.jpg' },
      { name: 'سوبريم', price: 18, desc: 'لوتس - نوتيلا - بيستاشيو', image: 'https://o2bot-b7a51.web.app/menu/cake/28.jpg' },
      { name: 'كرانش بار', price: 15, image: 'https://o2bot-b7a51.web.app/menu/cake/23.jpg', active: false },
      { name: 'موس', price: 10, desc: 'كيندر- لوتس - نوتيلا - بيستاشيو', image: 'https://o2bot-b7a51.web.app/menu/cake/4.jpg' },
      { name: 'تشيز كيك', price: 10, image: 'https://o2bot-b7a51.web.app/menu/cake/7.jpg' },
      { name: 'قالب نص بلاطة', price: 150, image: 'https://o2bot-b7a51.web.app/menu/cake/8.1.jpg' },
    ]),
  },
  barSweets: {
    title: 'حلويات البار',
    items: A([
      { name: 'كريب شوكولاتة', price: 15, image: 'https://o2bot-b7a51.web.app/menu/bar/16.jpg', active: false },
      { name: 'كريب (نوتيلا / بيستاشيو / لوتس)', price: 25, image: 'https://o2bot-b7a51.web.app/menu/bar/64.jpg' },
      { name: 'كريب دبي', price: 30, image: 'https://o2bot-b7a51.web.app/menu/bar/14.jpg' },
      { name: 'رينجز', price: 25, image: 'https://o2bot-b7a51.web.app/menu/bar/56.jpg' },
      { name: 'لقيمات شوكولاتة', price: 15, image: 'https://o2bot-b7a51.web.app/menu/bar/15.jpg', active: false },
      { name: 'لقيمات (نوتيلا / بيستاشيو / لوتس)', price: 25, image: 'https://o2bot-b7a51.web.app/menu/bar/55.jpg' },
      { name: 'بان كيك', price: 25, desc: 'نوتيلا / بيستاشيو / لوتس', image: 'https://o2bot-b7a51.web.app/menu/bar/67.jpeg' },
      { name: 'ميني بان كيك', price: 25, image: 'https://o2bot-b7a51.web.app/menu/bar/76.jpeg', desc: 'نوتيلا / بيستاشيو / لوتس' },
      { name: 'بان كيك شوكولاتة', price: 15, image: 'https://o2bot-b7a51.web.app/menu/bar/13.jpg', active: false },
      { name: 'مولتن كيك', price: 20, image: 'https://o2bot-b7a51.web.app/menu/bar/37.jpg' },
      { name: 'هوت كيك', price: 20, image: 'https://o2bot-b7a51.web.app/menu/bar/38.jpg' },
      { name: 'براونيز', price: 20, image: 'https://o2bot-b7a51.web.app/menu/bar/59.jpg' },
      { name: 'تاياكي', price: 25, image: 'https://o2bot-b7a51.web.app/menu/bar/67.jpeg' },
      { name: 'ميني فيشز', price: 25, image: 'https://o2bot-b7a51.web.app/menu/bar/68.jpeg', desc: 'نوتيلا / بيستاشيو / لوتس' },
      { name: 'وافل ستيك', price: 25, image: 'https://o2bot-b7a51.web.app/menu/bar/85.jpeg', desc: 'نوتيلا / بيستاشيو / لوتس' },
      { name: 'كنافة نويتلا', price: 15, image: 'https://o2bot-b7a51.web.app/menu/bar/58.jpg' },
    ]),
  },
  gelato: {
    title: 'الجيلاتو',
    items: A([
      { name: 'جيلاتو نوتيلا', price: 15, image: 'https://o2bot-b7a51.web.app/menu/Gelato/93.jpeg' },
      { name: 'جيلاتو بستاشيو', price: 15, image: 'https://o2bot-b7a51.web.app/menu/Gelato/72.jpeg' },
      { name: 'جيلاتو لوتس', price: 15, image: 'https://o2bot-b7a51.web.app/menu/Gelato/70.jpeg' },
      { name: 'جيلاتو كيندر', price: 15, image: 'https://o2bot-b7a51.web.app/menu/Gelato/95.jpeg' },
      { name: 'جيلاتو بلوبيري', price: 15, image: 'https://o2bot-b7a51.web.app/menu/Gelato/79.jpeg' },
      { name: 'جيلاتو عربية', price: 15, image: 'https://o2bot-b7a51.web.app/menu/Gelato/75.jpeg', active: false },
      { name: 'جيلاتو كراميل', price: 15, image: 'https://o2bot-b7a51.web.app/menu/Gelato/75.jpeg' },
    ]),
  },
  drinks: {
    title: 'المشروبات',
    items: A([
      { name: 'عصير الموسم', price: 12, image: 'https://o2bot-b7a51.web.app/menu/drinks/1.jpg' },
      { name: 'عصير أناناس', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/2.jpg' },
      { name: 'ليمون ونعنع', price: 12, image: 'https://o2bot-b7a51.web.app/menu/drinks/3.jpg' },
      { name: 'أفوكادو', price: 15, image: 'https://o2bot-b7a51.web.app/menu/drinks/4.jpg' },
      { name: 'شوكو بارد', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/7.jpg' },
      { name: 'ايس موكا', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/5.jpg' },
      { name: 'آيس كافي', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/10.jpg' },
      { name: 'ميلك شيك اسبشل', price: 20, image: 'https://o2bot-b7a51.web.app/menu/drinks/8.jpg', desc: 'نوتيلا / بستاشيو / لوتس' },
      { name: 'موهيتو', price: 20, image: 'https://o2bot-b7a51.web.app/menu/drinks/16.jpg' },
      { name: 'نسكافيه', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/9.jpg' },
      { name: 'كابتشينو', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/9.jpg' },
      { name: 'اسبريسو سينجل', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/6.jpg' },
      { name: 'اسبريسو دبل', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/6.jpg' },
      { name: 'قهوة تركي سينجل', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/6.jpg' },
      { name: 'قهوة تركي دبل', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/6.jpg' },
      { name: 'شاي', price: 3, image: 'https://o2bot-b7a51.web.app/menu/drinks/11.jpg' },
      { name: 'بلو', price: 4, image: 'https://o2bot-b7a51.web.app/menu/drinks/17.jpg' },
      { name: 'كوكا كولا', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/18.jpg' },
      { name: 'سبرايت', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/19.jpg' },
      { name: 'مياه معدنية 200 ملم', price: 1, image: 'https://o2bot-b7a51.web.app/menu/drinks/12.jpg' },
      { name: 'مياه معدنية 500 ملم', price: 2, image: 'https://o2bot-b7a51.web.app/menu/drinks/13.jpg' },
    ]),
  },
  salads: {
    title: 'السلطات',
    items: A([
      { name: 'سلطات مشكلة', image: 'https://o2bot-b7a51.web.app/menu/salad/89.jpeg', variants: [{ name: 'كبير', price: 15 }, { name: 'وسط', price: 10 }] },
      { name: 'ذرة مايونيز', image: 'https://o2bot-b7a51.web.app/menu/salad/5.jpeg', variants: [{ name: 'وسط', price: 10 }, { name: 'صغير', price: 5 }] },
      { name: 'بيكانتي', image: 'https://o2bot-b7a51.web.app/menu/salad/1.jpeg', desc: 'ذرة مايونيز / بيكانتي / تركية / ثومية', variants: [{ name: 'وسط', price: 10 }, { name: 'صغير', price: 5 }] },
      { name: 'تركية', image: 'https://o2bot-b7a51.web.app/menu/salad/4.jpeg', variants: [{ name: 'وسط', price: 10 }, { name: 'صغير', price: 5 }] },
      { name: 'ثومية', image: 'https://o2bot-b7a51.web.app/menu/salad/2.jpeg', variants: [{ name: 'وسط', price: 10 }, { name: 'صغير', price: 5 }] },
      { name: 'ملفوف', image: 'https://o2bot-b7a51.web.app/menu/salad/3.jpeg', variants: [{ name: 'وسط', price: 10 }, { name: 'صغير', price: 5 }] },
      { name: 'كول سلو', image: 'https://o2bot-b7a51.web.app/menu/salad/6.jpeg', variants: [{ name: 'وسط', price: 10 }, { name: 'صغير', price: 5 }] },
      { name: 'بطاطا', active: true, image: 'https://o2bot-b7a51.web.app/menu/salad/20.jpeg', price: 10 },
    ]),
  },
};

/* ══════════════════ الفرع الأوسط ══════════════════ */
const middleMenu = {
  shawarma: gazaMenu.shawarma,
  italian: {
    title: 'الإيطالي',
    items: A([
      { name: 'كاليزوني دجاج', price: 30, desc: 'صدر دجاج - جبنة - زيتون - رانش', image: 'https://o2bot-b7a51.web.app/menu/italian/35.jpg' },
      { name: 'كاليزوني دجاج + شيبس', price: 35, desc: 'صدر دجاج - جبنة - زيتون - رانش', image: 'https://o2bot-b7a51.web.app/menu/italian/91.jpeg' },
      { name: 'كاليزوني خضار', price: 20, desc: 'فليفلة - بصل - ذرة - مشروم - زيتون', image: 'https://o2bot-b7a51.web.app/menu/italian/36.jpg' },
      { name: 'بيتزا مكسيكي دجاج', price: 25, desc: 'صدر دجاج - جبنة - زيتون', image: 'https://o2bot-b7a51.web.app/menu/italian/33.jpg' },
      { name: 'ميجا', price: 35, desc: 'صدر دجاج - فليفلة - مشروم - جرادة - بصل - كريمة طعام', image: 'https://o2bot-b7a51.web.app/menu/italian/34.jpg' },
      { name: 'بيتزا خضار', price: 20, desc: 'خضار - ذرة - زيتون', image: 'https://o2bot-b7a51.web.app/menu/italian/32.jpg', active: true },
      { name: 'بيتزا ماما روزا بالاناناس', price: 20, desc: 'أناناس', image: 'https://o2bot-b7a51.web.app/menu/italian/2.jpg' },
      { name: 'نابولي', price: 20, desc: 'بيتزا بالتونة والزيتون', image: 'https://o2bot-b7a51.web.app/menu/italian/3.jpg' },
      { name: 'مارجريتا', price: 20, desc: 'جبنة', image: 'https://o2bot-b7a51.web.app/menu/italian/1.jpg' },
      { name: 'صوص رانش', price: 3, image: 'https://o2bot-b7a51.web.app/menu/italian/7.jpeg' },
    ]),
  },
  sandwiches: {
    title: 'السندويشات الغربية',
    items: A([
      { name: 'زينجر', price: 30, desc: 'شرائح صدر دجاج متبّلة مع بندورة طازجة، جرجير، حلقات بصل', image: 'https://o2bot-b7a51.web.app/menu/western/44.jpg' },
      { name: 'بيف برجر', price: 30, desc: 'قطعة لحمة - بصل - بندورة - جبنة - مخلل - صوص بيكانتي', image: 'https://o2bot-b7a51.web.app/menu/western/40.jpg' },
      { name: 'بيغ ماك', price: 40, desc: 'قطعتين لحمة - بصل - بندورة - جبنة - مخلل - صوص بيكانتي', image: 'https://o2bot-b7a51.web.app/menu/western/46.jpg' },
      { name: 'تشكن بيتزا', price: 30, desc: 'صدر دجاج - مشروم - فليفلة - بصل - زيتون اسود - جبنة', image: 'https://o2bot-b7a51.web.app/menu/western/94.jpg' },
      { name: 'شيش طاووق', price: 30, desc: 'فخد دجاج - جرجير - بندورة -مخلل -صوص بيكانتي', image: 'https://o2bot-b7a51.web.app/menu/western/47.jpg' },
      { name: 'فطيرة الذهبية', price: 30, desc: 'صدر دجاج - فليفلة - بصل - زيتون اسود - جبنة - ذرة - كريمة طعام', image: 'https://o2bot-b7a51.web.app/menu/western/43.jpg' },
      { name: 'تشكن فرايز', price: 30, image: 'https://o2bot-b7a51.web.app/menu/western/100.png' },
    ]),
  },
  easternSweets: gazaMenu.easternSweets,
  westernSweets: {
    title: 'الكيك والحلويات الغربية',
    items: A([
      { name: 'قالب كيك صغير', price: 60, image: 'https://o2bot-b7a51.web.app/menu/cake/9.jpg' },
      { name: 'قالب كيك كبير', price: 80, image: 'https://o2bot-b7a51.web.app/menu/cake/10.jpg' },
      { name: 'قالب كيك اسبيسشل صغير', price: 80, image: 'https://o2bot-b7a51.web.app/menu/cake/38.jpg' },
      { name: 'قالب كيك اسبيسشل كبير', price: 100, image: 'https://o2bot-b7a51.web.app/menu/cake/88.jpeg' },
      { name: 'سويس رول', price: 8, image: 'https://o2bot-b7a51.web.app/menu/cake/31.jpg' },
      { name: 'قطع كيك كلاسيكي', price: 5, image: 'https://o2bot-b7a51.web.app/menu/cake/5.jpg' },
      { name: 'تريلتشا', price: 10, image: 'https://o2bot-b7a51.web.app/menu/cake/21.jpg', active: false },
      { name: 'قطع كيك سبيشل', price: 10, desc: 'نوتيلا / بيستاشيو / لوتس', image: 'https://o2bot-b7a51.web.app/menu/cake/30.jpg' },
      { name: 'سوبريم', price: 18, desc: 'لوتس - نوتيلا - بيستاشيو', image: 'https://o2bot-b7a51.web.app/menu/cake/28.jpg' },
      { name: 'كرانش بار', price: 15, image: 'https://o2bot-b7a51.web.app/menu/cake/23.jpg', active: false },
      { name: 'موس', price: 10, desc: 'كيندر- لوتس - نوتيلا - بيستاشيو', image: 'https://o2bot-b7a51.web.app/menu/cake/4.jpg' },
      { name: 'تشيز كيك', price: 10, image: 'https://o2bot-b7a51.web.app/menu/cake/7.jpg' },
      { name: 'قالب نص بلاطة', price: 150, image: 'https://o2bot-b7a51.web.app/menu/cake/8.1.jpg' },
    ]),
  },
  barSweets: gazaMenu.barSweets,
  drinks: {
    title: 'المشروبات',
    items: A([
      { name: 'عصير الموسم', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/1.jpg', active: false },
      { name: 'عصير فراولة', price: 12, image: 'https://o2bot-b7a51.web.app/menu/drinks/1.jpg' },
      { name: 'عصير برتقال', price: 12, image: 'https://o2bot-b7a51.web.app/menu/drinks/2.jpg' },
      { name: 'عصير شمام', price: 12, image: 'https://o2bot-b7a51.web.app/menu/drinks/3.jpg' },
      { name: 'عصير اناناس', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/2.jpg' },
      { name: 'عصير خوخ', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/2.jpg' },
      { name: 'ليمون ونعنع', price: 12, image: 'https://o2bot-b7a51.web.app/menu/drinks/3.jpg' },
      { name: 'أفوكادو', price: 15, image: 'https://o2bot-b7a51.web.app/menu/drinks/4.jpg' },
      { name: 'عصير مانجا', price: 12, image: 'https://o2bot-b7a51.web.app/menu/drinks/2.jpg' },
      { name: 'شوكو بارد', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/7.jpg' },
      { name: 'ايس موكا', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/5.jpg' },
      { name: 'آيس كافي', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/10.jpg' },
      { name: 'ميلك شيك', price: 20, image: 'https://o2bot-b7a51.web.app/menu/drinks/8.jpg', desc: 'نوتيلا / بيستاشيو / لوتس' },
      { name: 'موهيتو', price: 20, image: 'https://o2bot-b7a51.web.app/menu/drinks/16.jpg' },
      { name: 'نسكافيه', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/9.jpg' },
      { name: 'كابتشينو', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/9.jpg' },
      { name: 'اسبريسو سينجل', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/6.jpg' },
      { name: 'اسبريسو دبل', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/6.jpg' },
      { name: 'قهوة تركي سينجل', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/6.jpg' },
      { name: 'قهوة تركي دبل', price: 10, image: 'https://o2bot-b7a51.web.app/menu/drinks/6.jpg' },
      { name: 'شاي', price: 3, image: 'https://o2bot-b7a51.web.app/menu/drinks/11.jpg' },
      { name: 'بلو', price: 4, image: 'https://o2bot-b7a51.web.app/menu/drinks/17.jpg' },
      { name: 'كوكا كولا', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/18.jpg' },
      { name: 'سبرايت', price: 5, image: 'https://o2bot-b7a51.web.app/menu/drinks/19.jpg' },
      { name: 'مياه معدنية 200 ملم', price: 1, image: 'https://o2bot-b7a51.web.app/menu/drinks/12.jpg' },
      { name: 'مياه معدنية 500 ملم', price: 2, image: 'https://o2bot-b7a51.web.app/menu/drinks/13.jpg' },
    ]),
  },
  salads: gazaMenu.salads,
  gelato: gazaMenu.gelato,
};

const BRANCHES = [
  { id: 'gaza', label: 'فرع غزة' },
  { id: 'middle', label: 'الفرع الأوسط' },
];

const branchMenuData = { gaza: gazaMenu, middle: middleMenu };

module.exports = { categoryNames, categoryEmoji, branchMenuData, BRANCHES };
